export const metadata = {
  title: "Client Site",
  description: "Generated by FlorishOnline",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
